export const EMAIL_WHITELIST_CHECK_REQUEST = 'EMAIL_WHITELIST_CHECK_REQUEST';
export const EMAIL_WHITELIST_CHECK_SUCCESS = 'EMAIL_WHITELIST_CHECK_SUCCESS';
export const EMAIL_WHITELIST_CHECK_FAIL = 'EMAIL_WHITELIST_CHECK_FAIL';

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';

export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAIL = 'LOGOUT_USER_FAIL';

export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const RESET_STATE = 'RESET_STATE';
